version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
        fingerprints:
          - "MD5:42:8c:0e:d9:ed:0a:2f:c7:d5:6c:48:0f:c6:e1:66:db"
      - run:
          name: Deploy Over SSH
          command: ssh -o PubkeyAuthentication=no jswebdev@jswebdev.ftp.tools
